name: Architecture Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  architecture-tests:
    name: Clean Architecture Compliance
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Select Xcode version
      run: sudo xcode-select -s /Applications/Xcode_15.2.app
      
    - name: Show Xcode version
      run: xcodebuild -version
      
    - name: Run Architecture Tests
      run: |
        xcodebuild test \
          -project ThreadJournal2.xcodeproj \
          -scheme ThreadJournal2 \
          -destination 'platform=iOS Simulator,name=iPhone 15' \
          -only-testing:ThreadJournal2Tests/ArchitectureCITests \
          | xcpretty --test --color
      
    - name: Upload test results
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          ~/Library/Developer/Xcode/DerivedData/**/Logs/Test/*.xcresult
        retention-days: 5